### ISSUE TITLE
Cycle detected when const-evaluating NAN

### ISSUE THREAD

**Issue by eliaslevy** [olson-sean-k/decorum#23]
Newer versions of `decorum` (0.2.0 or later) fail to compile using Rust 1.42.0 with the error:
```
error[E0391]: cycle detected when const-evaluating + checking `primitive::<impl at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/decorum-0.3.1/src/primitive.rs:23:9: 29:10>::NAN`
```

If there is some incompatibility and there is a minimal supported version of Rust, this should be explained in the README.

**Comment by olson-sean-k** [comment]
Beginning with 0.2.0, Decorum uses associated constants on primitive types [introduced in Rust 1.43.0](https://github.com/rust-lang/rust/blob/033f6899f72464f7477092eb4ce872cf2a097114/RELEASES.md#libraries-1). I believe that is currently the minimum supported version of Rust, but I'll need to verify that to be sure. I'll mention this in the README and include the minimum supported version in CI.

**Comment by olson-sean-k** [comment]
80285ad documents a minimum supported version of Rust in the README and library documentation and enables tests against that version of the toolchain in CI. Please reopen if you think something is missing and thanks for reporting this.
